
INSERT INTO Moods
  (mood)
VALUES
  ('Break-up'),  -- the mid starts here from 1 and so on
  ('Popular'),
  ('Work-out'),
  ('EDM'),
  ('Caribbean'),
  ('Love');

INSERT INTO Songs
  (name, artist, url, explicit)
VALUES
('When I Was Your Man','Bruno Mars','https://youtu.be/ekzHIouo8Q4', 0),
  ('Someone Like You','Adele','https://youtu.be/hLQl3WQQoQ0', 0),
  ('Send My Love (To Your New Lover)','Adele','https://youtu.be/fk4BbF7B29w', 0),
  ("I'm Not The Only One",'Sam Smith','https://youtu.be/nCkpzqqog4k', 0),
  ("I hate you, I love you",'Gnash','https://youtu.be/BiQIc7fG9pA', 1),
  ('Little Do You Know','Alex & Sierra' ,'https://youtu.be/4bzIpYiPUUo', 0),
  ('Sorry','Halsey','https://youtu.be/tEnCoocmPQM', 0),
  ('Cold/mess','Prateek Kuhad','https://youtu.be/Il7Nv270zNk', 0),
  ("Thank u, next",'Ariana Grande','https://youtu.be/gl1aHhXnN1k', 0),
  ('Wrecking Ball','Miley Cyrus','https://youtu.be/My2FRPA3Gf8', 0),
  ('We Are Never Ever Getting Back Together','Taylor Swift','https://youtu.be/WA4iX5D9Z64', 0),
  ("We Don't Talk Anymore",'Charlie Puth','https://youtu.be/3AtDnEC4zak', 0),
  ('Rolling in the Deep','Adele','https://youtu.be/rYEDA3JcQqw', 0),
  ('Say Something','A Great Big World','https://youtu.be/-2U0Ivkn2Ds', 0),
  ('Too Good at Goodbyes','Sam Smith','https://youtu.be/J_ub7Etch2U', 0),
  ('Stay','Rihanna','https://youtu.be/JF8BRvqGCNs', 0),
  ('I Knew You Were Trouble','Taylor Swift','https://youtu.be/vNoKguSdy4Y', 0),
  ('Before He Cheats','Carrie Underwood','https://youtu.be/WaSy8yy-mr8', 0),
  ("I Can't Make You Love Me",'Bonnie Raitt','https://youtu.be/nW9Cu6GYqxo', 0),
  ('Dancing on My Own','Calum Scott','https://youtu.be/q31tGyBJhRY', 0),
  ('Heartless','Kanye West','https://youtu.be/Co0tTeuUVhU', 0),
  ( 'The Box', 'Roddy Rich', 'https://www.youtube.com/watch?v=uLHqpjW3aDs', 1),
  ('Physical', 'Dua Lipa', 'https://www.youtube.com/watch?v=SRdlnO9gMIY', 0),
  ( 'Say So', 'Doja Cat', 'https://www.youtube.com/watch?v=pok8H_KF1FA', 1),
  ( 'Intentions', 'Justin Bieber ft. Quavo', 'https://www.youtube.com/watch?v=kviFimaREU4', 0),
  ( 'Life is Good', 'Drake and Future', 'https://www.youtube.com/watch?v=2-UaLcH5tCw', 1),
  ( 'bad guy', 'Billie Eilish', 'https://www.youtube.com/watch?v=4-TbQnONe_w', 0),
  ( 'My Oh My', 'Camila Cabello ft. DaBaby', 'https://www.youtube.com/watch?v=6fd2kkLmSDQ', 1),
  ( 'Yummy', 'Justin Bieber', 'https://www.youtube.com/watch?v=JwzIGTlXOHM', 0),
  ( 'Roxanne', 'Arizona Zervas', 'https://www.youtube.com/watch?v=0-YlrjvEqoM', 1),
  ( 'Memories', 'Maroon 5', 'https://www.youtube.com/watch?v=o2DXt11SMNI', 0),
  ( 'Heartless', 'The Weeknd', 'https://www.youtube.com/watch?v=1DpH-icPpl0', 1),
  ( 'Falling', 'Harry Styles', 'https://www.youtube.com/watch?v=zPY4s6yMYkE', 0),
  ( 'Own It', 'Stormzy ft. Burna Boy and Ed Sheeran', 'https://www.youtube.com/watch?v=eYwbGaSurCQ', 1),
  ( 'Circles', 'Post Malone', 'https://www.youtube.com/watch?v=0sca9FP6zl8', 1),
  ( 'hot girl bummer', 'blackbear', 'https://www.youtube.com/watch?v=k-T4Odb-r5c', 1),
  ( 'La Difícil', 'Bad Bunny', 'https://www.youtube.com/watch?v=fEYUoBgYKzw', 1),
  ('Time', 'Childish Gambino ft. Ariana Grande', 'https://www.youtube.com/watch?v=5pFm_lszTv8', 1),
  ( 'Stained Glass', 'Madison Beer', 'https://www.youtube.com/watch?v=B67UN35aVWs', 0),
  ( 'Like That', 'Doja Cat ft. Gucci Mane', 'https://www.youtube.com/watch?v=iEd-I2mL20Y', 1),
  ( 'Actions', 'John Legend', 'https://www.youtube.com/watch?v=JWxizlCWjho', 0),
  ( 'u know it’s real', 'Ant Saunders', 'https://www.youtube.com/watch?v=ilHKBCVlklU', 0),
  ( 'Man of THe Year', 'ScHoolboy Q', 'https://www.youtube.com/watch?v=2lzD5NTs3l0', 1),
  ( 'Welcome to The Party', 'Pop Smoke', 'https://www.youtube.com/watch?v=usu0XY4QNB0', 1),
  ( 'Ballin', 'Roddy Ricch', 'https://www.youtube.com/watch?v=xkibCjoGZs4', 1),
  ( 'Bop', 'DaBaby', 'https://www.youtube.com/watch?v=MKr_idr2EwQ', 1),
  ( 'Savage', 'Megan Thee Stallion', 'https://www.youtube.com/watch?v=eJEKHdvntPI', 1),
  ( 'Bacc Seat', 'Roddy Ricch ft. Ty Dolla $ign', 'https://www.youtube.com/watch?v=yYliDCjxBaI', 1),
  ( 'WHATS POPPIN', 'Jack Harlow', 'https://www.youtube.com/watch?v=IgL78BpE5fw', 1),
  ( 'Smack A Bitch', 'Rico Nasty', 'https://www.youtube.com/watch?v=-D4happ4TQU', 1),
  ( 'B.I.T.C.H.', 'Megan Thee stallion', 'https://www.youtube.com/watch?v=1mNCReRRnVw', 1),
  ( 'Stick Together', 'Rich The Kid ft. Lil Baby', 'https://www.youtube.com/watch?v=uvwUuKIT33c', 1),
  ( 'Thot Box (Remix)', 'Hitmaka', 'https://www.youtube.com/watch?v=gKgD3qn4yk0', 1),
  ( 'Realer', 'Megan Thee Stallion', 'https://www.youtube.com/watch?v=6BlWUh_iOKk', 1),
  ( 'Sum 2 Prove', 'Lil Baby', 'https://www.youtube.com/watch?v=lr31Nq8B-Ho', 1),
  ( 'Dior', 'Pop Smoke', 'https://www.youtube.com/watch?v=goYgHnsQdtY', 1),
  ('Chanel Slides', 'Dreezy ft. Kash Doll', 'https://www.youtube.com/watch?v=mpAdintyiV8', 1),
  ( 'Walker Texas Ranger', 'DaBaby', 'https://www.youtube.com/watch?v=gV6_-uSP4a8', 1),
  ('Big Bank', 'YG', 'https://www.youtube.com/watch?v=m8agkKbGCzM', 1),
  ( 'Ego', 'Jay Critch', 'https://www.youtube.com/watch?v=YmMruNsDb6E', 1),
  ( 'Down Bad', 'Dreamville', 'https://www.youtube.com/watch?v=lIM1hejXzhw', 1),
  ( 'Costa Rica', 'Dreamville', 'https://www.youtube.com/watch?v=Zn8ohtUY44g', 1),
  ( 'When in Rome - Steve Brian Remix', 'GATTÜSO', 'https://www.youtube.com/watch?v=otwvEKZZreo', 0),
  ( 'L’Amour Toujours', 'Gigi D’Agostino', 'https://www.youtube.com/watch?v=w15oWDh02K4', 0),
  ( 'There For You', 'Martin Garrix', 'https://www.youtube.com/watch?v=pNNMr5glICM', 0),
  ( 'Pizza', 'Martin Garrix', 'https://www.youtube.com/watch?v=JsKIAO11q1Y', 0),
  ( 'High On Life', 'Martin Garrix', 'https://www.youtube.com/watch?v=Lpjcm1F8tY8', 0),
  ( 'Mistaken', 'Martin Garrix', 'https://www.youtube.com/watch?v=9-klJ6EQfe8', 0),
  ( 'Like I Do', 'Martin Garrix ft David Guetta', 'https://www.youtube.com/watch?v=WfPu9Jrcpuk', 0),
  ( 'Yottabyte', 'Martin Garrix', 'https://www.youtube.com/watch?v=WTrFa9H_lpk', 0),
  ( 'Years', 'Alesso ft Matthew Kona', 'https://www.youtube.com/watch?v=EGYaxYaxD_M', 0),
  ( 'Turn It Around', 'Dubvision', 'https://www.youtube.com/watch?v=rvZWsr4QCRc', 0),
  ( 'Pressure - Alesso Radio Edit', 'Nadi Ali', 'https://www.youtube.com/watch?v=SU88c0f5-h0', 0),
  ( 'Walk On Water', 'GATTÜSO', 'https://www.youtube.com/watch?v=U-R3zUSdIP0', 0),
  ( 'Million Miles', 'Mark Sixma', 'https://www.youtube.com/watch?v=fxSyswLTflg', 0),
  ( 'Lullaby - GATTÜSO Remix', 'R3HAB & Mike Williams', 'https://www.youtube.com/watch?v=qrwBbv0ivjs', 0),
  ( 'Too Real', 'Kerwin Du Bois', 'https://www.youtube.com/watch?v=74pYwmtzl24', 0),
  ( 'Wotless', 'Kes', 'https://www.youtube.com/watch?v=n0DvbOk8rs4', 0),
  ( 'Soca Demon', 'Kerwin Du Bois', 'https://www.youtube.com/watch?v=bTU87Tdndvc', 0),
  ( 'Bruk Off Yuh Back', 'Koshens', 'https://www.youtube.com/watch?v=N8CCuhSbgyE', 1),
  ( 'All On Me', 'Gyptian', 'https://www.youtube.com/watch?v=hYCFxl57qyU', 0),
  ( 'Wine Up On Me', 'Zoelah', 'https://www.youtube.com/watch?v=Z7hwJv9hjgY', 0),
  ( 'Wine For Me', 'Popcaan', 'https://www.youtube.com/watch?v=tDsfZVrs3j8', 0),
  ( 'Roll It Gal', 'Alison Hinds', 'https://www.youtube.com/watch?v=R7xKNbflCtc', 0),
  ( 'Fast Wine', 'Machel Montano', 'https://www.youtube.com/watch?v=p0JmdoSkfZ0', 0),
  ( 'Turn Me On', 'Kevin Lyttle', 'https://www.youtube.com/watch?v=GP3Exc5tCtc', 0),
  ( 'Yuh Love', 'Vybz Kartel', 'https://www.youtube.com/watch?v=-yqaFp981Yw', 0),
  ( 'Overdue', 'Erphaan Alves', 'https://www.youtube.com/watch?v=3o4PjGj68RQ', 0),
  ( 'A Little Wine', 'Patrice Roberts', 'https://www.youtube.com/watch?v=y7v4UvvdgwE', 0),
  ( 'Ova Dweet', 'Popcaan', 'https://www.youtube.com/watch?v=r_FX6UANhLs', 0),
  ('My Heart Will Go On','Céline Dion','https://youtu.be/ea2kr3yTpFw', 0),
  ('All of Me','John Legend','https://youtu.be/450p7goxZqg', 0),
  ('Thinking Out Loud','Ed Sheeran','https://youtu.be/lp-EO5I60KA', 0),
  ("Let's Stay Together",'Al Green','https://youtu.be/COiIC3A0ROM', 0),
  ('I Will Always Love You','Whitney Houston','https://youtu.be/3JWTaaS7LdU', 0),
  ('Love Story','Taylor Swift','https://youtu.be/8xg3vE8Ie_E', 0),
  ("Cant Help Falling in Love",'Elvis Presley','https://youtu.be/vGJTaP6anOU', 0),
  ('How Deep Is Your Love','Bee Gees','https://youtu.be/XpqqjU7u5Yc', 0),
  ('A Thousand Years','Christina Perri','https://youtu.be/rtOvBOTyX00', 0),
  ('Perfect','Ed Sheeran','https://youtu.be/2Vv-BfVoq4g', 0),
  ('Love Me Like You Do','Ellie Goulding','https://youtu.be/eVVaqFDG6Fo', 0),
  ('Drunk in Love','Beyoncé','https://youtu.be/p1JPKLa-Ofc', 1),
  ("Say You Won't Let Go",'James Arthur','https://youtu.be/0yW7w8F2TVA', 0),
  ('Call it what you want','Taylor Swift','https://youtu.be/V54CEElTF_U', 0),
  ('Crazy In Love','Beyoncé' ,'https://youtu.be/ViwtNLUqkMY', 0),
  ('Bleeding Love','Leona Lewis','https://youtu.be/Vzo-EL_62fQ', 0),
  ('Right Here Waiting','Richard Marx' ,'https://youtu.be/S_E2EHVxNAE', 0),
  ('Ek Villain','Ankit Tiwari','https://youtu.be/FxAG_11PzCk', 0),
  ('Love Me Now','John Legend','https://youtu.be/NmCFY1oYDeM', 0),
  ("Like I'm Gonna Lose You",'Meghan Trainor','https://youtu.be/2-MBfn8XjIU', 0),
  ('Love Song','Sara Bareilles','https://youtu.be/qi7Yh16dA0w', 0);

INSERT INTO SongMood
  (sid, mid)
VALUES
  (10, 2),
  (10, 6)
  (1, 1),
  (2, 1),
  (3, 1),
  (4, 1),
  (5, 1),
  (6, 1),
  (7, 1),
  (8, 1),
  (9, 1),
  (10, 1),
  (11, 1),
  (12, 1),
  (13, 1),
  (14, 1),
  (15, 1),
  (16, 1),
  (17, 1),
  (18, 1),
  (19, 1),
  (20, 1),
  (21, 1),
  (22, 2),
  (23, 2),
  (24, 2),
  (25, 2),
  (26, 2),
  (27, 2),
  (28, 2),
  (29, 2),
  (30, 2),
  (31, 2),
  (32, 2),
  (33, 2),
  (34, 2),
  (35, 2),
  (36, 2),
  (37, 2),
  (38, 2),
  (39, 2),
  (40, 2),
  (41, 2),
  (42, 2),
  (43, 3),
  (44, 3),
  (45, 3),
  (46, 3),
  (47, 3),
  (48, 3),
  (49, 3),
  (50, 3),
  (51, 3),
  (52, 3),
  (53, 3),
  (54, 3),
  (55, 3),
  (56, 3),
  (57, 3),
  (58, 3),
  (59, 3),
  (60, 3),
  (61, 3),
  (62, 3),
  (63, 4),
  (64, 4),
  (65, 4),
  (66, 4),
  (67, 4),
  (68, 4),
  (69, 4),
  (70, 4),
  (71, 4),
  (72, 4),
  (73, 4),
  (74, 4),
  (75, 4),
  (76, 4),
  (77, 5),
  (78, 5),
  (79, 5),
  (80, 5),
  (81, 5),
  (82, 5),
  (83, 5),
  (84, 5),
  (85, 5),
  (86, 5),
  (87, 5),
  (88, 5),
  (89, 5),
  (90, 5),
  (91, 6),
  (92, 6),
  (93, 6),
  (94, 6),
  (95, 6),
  (96, 6),
  (97, 6),
  (98, 6),
  (99, 6),
  (100, 6),
  (101, 6),
  (102, 6),
  (103, 6),
  (104, 6),
  (105, 6),
  (106, 6),
  (107, 6),
  (108, 6),
  (109, 6),
  (110, 6),
  (111, 6);

INSERT INTO Suggestions
  (username, songname, artist, url, moodname, comment)
VALUES
  ('username', 'songname', 'artist', 'url', 'moodname', 'comment');
